# Opções de JVM usadas pelo daemon do Gradle.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Habilita AndroidX.
android.useAndroidX=true

# Habilita o cache de configuração do Gradle para builds mais rápidos.
org.gradle.configuration-cache=true

# Estilo de código Kotlin oficial.
kotlin.code.style=official

# Usa R por módulo.
android.nonTransitiveRClass=true
